### ISSUE TITLE
Hot Restart is broken on iOS 15 [and how to fix it]

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#12915]
Since bits and pieces of Hot Restart are closed source and bits are open source I am cross-posing here what is broken and steps on how to fix it. As reported on [the community forum](https://developercommunity.visualstudio.com/t/Xamarin-iOS-deployment-failing-after-iOS/1541200) Hot Restart stopped working on iOS 15. I managed to get it working locally and here are all the things I had to fix:

1) iOS 15 now strictly requires the [DER-encoded entitlements to be present](https://developer.apple.com/documentation/Xcode/using-the-latest-code-signature-format). The current code in the closed source iSign.Core.dll doesn't currently support that. **(Update: Fixed in Hot Restart Client 1.0.82)**
2) A bug in `iSign.Core` in the `ByteArrayExtensions.ReplaceBytes` method and its usage causes a wrong requirement blob to be generated. The method creates a new array with correct content and then immediately throws it away.  **(Update: Partially fixed in Hot Restart Client 1.0.82; still produces incorrect requirements because the fields are length prefixed)**
3) The order in which the bundle is produced and signed is incorrect. This is purely MSBuild thing but it causes a large part of the bundle to be unsigned.
4) Incorrectly calculated code directory hashes for the very last code block.  **(Update: Fixed in Hot Restart Client 1.0.82)**
5) Incorrect flags in Code Directory header preventing dynamic frameworks from working.  **(Update: Fixed in Hot Restart Client 1.0.82)**

**Comment by filipnavara** [comment]
Let's start with the easy one - fix MSBuild to sign the whole bundle by reversing the order of copying bundle contents and signing it:

```diff
--- a/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
+++ b/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.targets
@@ -150,6 +150,10 @@
 			<Output TaskParameter="AppBundlePath" PropertyName="HotRestartAppBundlePath" />
 		</PrepareAppBundle>
 
+		<PropertyGroup>
+			<HotRestartAppContentDir>$(HotRestartAppBundlePath)\$(_AppBundleName).content\</HotRestartAppContentDir>
+		</PropertyGroup>
+
 		<!-- Delete the build signature to force XMA do a full build next time -->
 		<Delete Files="$(BuildSignatureFile)" Condition="Exists('$(BuildSignatureFile)')"	/>
 
@@ -209,12 +213,12 @@
 		Condition="'$(_CanOutputAppBundle)' == 'true' And '$(IsAppExtension)' == 'false' And '$(IsHotRestartBuild)' == 'true'"
 		DependsOnTargets="_CreateHotRestartCachedBundle;_UnpackHotRestartLibraryResources"
 		Inputs="@(_HotRestartBundleResourceWithLogicalName);@(_FilesToHotRestartBundle)"
-		Outputs="@(_HotRestartBundleResourceWithLogicalName -> '$(HotRestartSignedAppDir)%(LogicalName)');
-			@(_FilesToHotRestartBundle -> '$(HotRestartSignedAppDir)%(Filename)%(Extension)')">
+		Outputs="@(_HotRestartBundleResourceWithLogicalName -> '$(HotRestartAppBundlePath)\%(LogicalName)');
+			@(_FilesToHotRestartBundle -> '$(HotRestartAppBundlePath)\%(Filename)%(Extension)')">
 
 		<!-- Copy Bundle resources -->
 		<Copy SourceFiles="@(_HotRestartBundleResourceWithLogicalName)"
-        DestinationFiles="@(_HotRestartBundleResourceWithLogicalName -> '$(HotRestartSignedAppDir)\%(LogicalName)')"
+        DestinationFiles="@(_HotRestartBundleResourceWithLogicalName -> '$(HotRestartAppBundlePath)\%(LogicalName)')"
         SkipUnchangedFiles="true"
         Condition="'@(_HotRestartBundleResourceWithLogicalName)' != ''">
 
@@ -222,7 +226,7 @@
 		</Copy>
 
 		<Copy SourceFiles="@(_FilesToHotRestartBundle)"
-        DestinationFiles="@(_FilesToHotRestartBundle -> '$(HotRestartSignedAppDir)\%(Filename)%(Extension)')"
+        DestinationFiles="@(_FilesToHotRestartBundle -> '$(HotRestartAppBundlePath)\%(Filename)%(Extension)')"
         SkipUnchangedFiles="true"
         Condition="'@(_FilesToHotRestartBundle)' != ''">
 
@@ -298,9 +302,9 @@
 
 	<PropertyGroup>
 		<_CreateHotRestartOutputBundleDependsOn>
-			_CodesignHotRestartAppBundle;
 			_CopyFilesToHotRestartBundle;
 			_CopyFilesToHotRestartContent;
+			_CodesignHotRestartAppBundle;
 		</_CreateHotRestartOutputBundleDependsOn>
 	</PropertyGroup>
 
--- a/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props
+++ b/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.HotRestart.props
@@ -8,7 +8,6 @@
 		<HotRestartPayloadDir>$(HotRestartSignedAppOutputDir)Payload\</HotRestartPayloadDir>
 		<HotRestartSignedAppDir>$(HotRestartPayloadDir)$(_AppBundleName).app\</HotRestartSignedAppDir>
 		<HotRestartContentDir>$(HotRestartSignedAppOutputDir)$(_AppBundleName).content\</HotRestartContentDir>
-		<HotRestartAppContentDir>$(HotRestartSignedAppDir)$(_AppBundleName).content\</HotRestartAppContentDir>
 		<HotRestartContentStampDir>$(HotRestartSignedAppOutputDir)$(_AppBundleName).stamp\</HotRestartContentStampDir>
 		<HotRestartIPAPath>$(HotRestartSignedAppOutputDir)$(_AppBundleName).ipa</HotRestartIPAPath>
 
```

The .NET 6 code is in this repository, the legacy Xamarin code is not and it would require similar fix.

**Comment by filipnavara** [comment]
Generating DER Entitlement is the tricky part. I cannot provide a straightforward patch since that part is closed source, but here are the necessary bits and pieces.

First, let's create a convertor for PList format to create a DER binary output. I used the `System.Formats.Asn1` library that is part of .NET but it must also be added to the list of distributed files. The PList code is already extensible and allows custom formats, so go ahead and add a new one:
```csharp
using System;
using System.Collections.Generic;
using System.Formats.Asn1;
using System.IO;

namespace iSign.Core
{
    public abstract partial class PropertyListFormat
    {
        public static readonly PropertyListFormat Der = (PropertyListFormat)new PropertyListFormat.DerFormat();

        private class DerFormat : PropertyListFormat
        {
            public override ReadWriteContext StartReading(Stream input)
            {
                throw new NotImplementedException();
            }

            public override ReadWriteContext StartWriting(Stream output)
            {
                return new Context(output);
            }

            private class Context : ReadWriteContext
            {
                private readonly Stream writer;
                private readonly AsnWriter asnWriter;
                private bool disposed;

                public Context(Stream writer)
                {
                    this.writer = writer;
                    this.asnWriter = new AsnWriter(AsnEncodingRules.DER);
                }

                protected override void ReadObjectHead() => throw new NotImplementedException();

                protected override bool ReadBool() => throw new NotImplementedException();

                protected override long ReadInteger() => throw new NotImplementedException();

                protected override double ReadReal() => throw new NotImplementedException();

                protected override DateTime ReadDate() => throw new NotImplementedException();

                protected override byte[] ReadData() => throw new NotImplementedException();

                protected override string ReadString() => throw new NotImplementedException();

                public override bool ReadArray(PArray array) => throw new NotImplementedException();

                public override bool ReadDict(PDictionary dict) => throw new NotImplementedException();

                protected override void Write(PBoolean boolean) => this.asnWriter.WriteBoolean(boolean.Value);

                protected override void Write(PNumber number) => this.asnWriter.WriteInteger(number.Value);

                protected override void Write(PReal real) => throw new NotImplementedException();

                protected override void Write(PDate date) => this.asnWriter.WriteUtcTime(date.Value);

                protected override void Write(PData data) => this.asnWriter.WriteOctetString(data.Value);

                protected override void Write(PString str) => this.asnWriter.WriteCharacterString(UniversalTagNumber.UTF8String, str.Value);

                protected override void Write(PArray array)
                {
                    using (this.asnWriter.PushSequence())
                    {
                        foreach (PObject pobject in array)
                        {
                            this.WriteObject(pobject);
                        }
                    }
                }

                protected override void Write(PDictionary dict)
                {
                    using (this.asnWriter.PushSetOf())
                    {
                        foreach (KeyValuePair<string, PObject> keyValuePair in dict)
                        {
                            using (this.asnWriter.PushSequence())
                            {
                                this.asnWriter.WriteCharacterString(UniversalTagNumber.UTF8String, keyValuePair.Key);
                                this.WriteObject(keyValuePair.Value);
                            }
                        }
                    }
                }

                public override void Dispose()
                {
                    if (disposed)
                        return;
                    var derSequence = this.asnWriter.Encode();
                    this.writer.Write(derSequence, 0, derSequence.Length);
                    this.writer.Dispose();
                    disposed = true;
                }
            }
        }
    }
}
```

Next up, modify couple of the data classes to hold the new information:
```csharp
    public partial class EntitlementDERBlob : BaseBlob
    {
        public override byte[] GetFullData()
        {
            using (EndianessAwareWriter endianessAwareWriter = new EndianessAwareWriter((Stream)new MemoryStream(), Endianess.BigEndian))
            {
                endianessAwareWriter.WriteUInt32((uint)this.Magic);
                byte[] bytes = OriginalBlobData; //this.EmitBlob();
                endianessAwareWriter.WriteInt32(bytes.Length + 8);
                endianessAwareWriter.WriteBytes(bytes, true);
                return (endianessAwareWriter.BaseStream as MemoryStream).ToArray();
            }
        }
    }

    public partial class SpecialSlotsData
    {
        public (byte[] Sha1, byte[] Sha256) DerEntitlements { get; set; }
    }
```

The update logic in `Executable` needs to be adjusted to calculate hashes and update the DER entitlement blob:
```csharp
        private void UpdateEntitlementsBlob(CodeSignatureBlob codeSignature, AppBundleResignData resignData)
        {
            BaseBlob baseBlob = codeSignature.SubBlobs.FirstOrDefault<BaseBlob>((Func<BaseBlob, bool>)(s => s.Magic == CodeSignatureMagic.CSMAGIC_ENTITLEMENT));
            if (baseBlob == null)
                throw new AppleSigningException("Initial signature is malformed: no entitlement blob found in the initial signature");
            (baseBlob as EntitlementBlob).Plist = resignData.Entitlements;
            byte[] fullData = baseBlob.GetFullData();
            resignData.SpecialSlotsData.Entitlements = resignData.SpecialSlotsData.GetHashCodes(fullData);

            // Also update the DER entitlement if it exists
            baseBlob = codeSignature.SubBlobs.FirstOrDefault<BaseBlob>((Func<BaseBlob, bool>)(s => s.Magic == CodeSignatureMagic.CSMAGIC_ENTITLEMENTDER));
            if (baseBlob != null)
            {
                (baseBlob as EntitlementDERBlob).OriginalBlobData = resignData.Entitlements.ToByteArray(PropertyListFormat.Der);
                fullData = baseBlob.GetFullData();
                resignData.SpecialSlotsData.DerEntitlements = resignData.SpecialSlotsData.GetHashCodes(fullData);
            }
        }

        private void UpdateSpecialSlots(SpecialSlotsData specialSlotsData, CodeSignatureBlob codeSignature)
        {
            foreach (CodeDirectory codeDirectory in codeSignature.SubBlobs.OfType<CodeDirectory>())
            {
                if ((int)codeDirectory.HashSize == (int)HashSize.Sha1)
                {
                    if (specialSlotsData.Entitlements.Sha1 != null)
                        codeDirectory.UpdateEntitlementsPlistSlot(specialSlotsData.Entitlements.Sha1);
                    if (specialSlotsData.DerEntitlements.Sha1 != null)
                        codeDirectory.UpdateDerEntitlementsPlistSlot(specialSlotsData.DerEntitlements.Sha1);
                    if (specialSlotsData.InternalRequirements.Sha1 != null)
                        codeDirectory.UpdateInternalRequirementsSlot(specialSlotsData.InternalRequirements.Sha1);
                    codeDirectory.UpdateResourceDirectoryPlistSlot(specialSlotsData.ResourceDirectory.Sha1);
                    codeDirectory.UpdateInfoPlistSlot(specialSlotsData.BoundInfoPlist.Sha1);
                }
                else if ((int)codeDirectory.HashSize == (int)HashSize.Sha256)
                {
                    if (specialSlotsData.Entitlements.Sha256 != null)
                        codeDirectory.UpdateEntitlementsPlistSlot(specialSlotsData.Entitlements.Sha256);
                    if (specialSlotsData.DerEntitlements.Sha256 != null)
                        codeDirectory.UpdateDerEntitlementsPlistSlot(specialSlotsData.DerEntitlements.Sha256);
                    if (specialSlotsData.InternalRequirements.Sha256 != null)
                        codeDirectory.UpdateInternalRequirementsSlot(specialSlotsData.InternalRequirements.Sha256);
                    codeDirectory.UpdateResourceDirectoryPlistSlot(specialSlotsData.ResourceDirectory.Sha256);
                    codeDirectory.UpdateInfoPlistSlot(specialSlotsData.BoundInfoPlist.Sha256);
                }
            }
        }
```

Finally, when generating empty signature in `CodeSignatureBlob.EmitEmptyBlobForArchive` the DER entitlement blob also has to be generated. That means increasing the blob count in the header: `bundle.BundleType == BundleType.Application ? 6 : 4` and then actually generating it:
```csharp
                    byteArray = entitlementPList.ToByteArray(PropertyListFormat.Der);
                    EntitlementDERBlob entitlementDerBlob = new EntitlementDERBlob(0, byteArray.Length, byteArray);
                    baseBlobList.Insert(3, (BaseBlob)entitlementDerBlob);
```

Since the has for the DER entitlement blob is now also calculated in special slot -7 we need to increase the number of special slots in `ApplicationBundle` from 5 to 7: `public override int NumberOfSpecialSlots => 7;`.

**Comment by filipnavara** [comment]
Finally, let's fix that pesky bug in the requirements generation by updating `ByteArrayExtensions`:
```csharp
        public static byte[] ReplaceBytes(this byte[] src, byte[] search, byte[] repl)
        {
            int bytes = FindBytes(src, search);
            if (bytes >= 0)
            {
                byte[] newArray = new byte[src.Length - search.Length + repl.Length];
                Buffer.BlockCopy(src, 0, newArray, 0, bytes);
                Buffer.BlockCopy(repl, 0, newArray, bytes, repl.Length);
                Buffer.BlockCopy(src, bytes + search.Length, newArray, bytes + repl.Length, src.Length - (bytes + search.Length));
                return newArray;
            }
            return src;
        }
```
and the caller:
```csharp
        private static byte[] GetExecutableRequirementsTemplate(string bundleIdentifier, string certificateFriendlyName)
        {
            using (MemoryStream memoryStream = new MemoryStream())
            {
                Assembly.GetExecutingAssembly().GetManifestResourceStream("iSign.Core.Resources.ExecutableRequirement.blob").CopyTo(memoryStream);
                byte[] array = memoryStream.ToArray();
                array = array.ReplaceBytes(Encoding.UTF8.GetBytes("com.companyname.FormsDebuggerTest"), Encoding.UTF8.GetBytes(bundleIdentifier));
                array = array.ReplaceBytes(Encoding.UTF8.GetBytes("iPhone Developer: Oleg Demchenko (NQPM8GL26B)"), Encoding.UTF8.GetBytes(certificateFriendlyName));
                return array;
            }
        }
```

**Comment by filipnavara** [comment]
cc @emaf @mauroa (no idea if Oleg Demchenko is on GitHub)

**Comment by filipnavara** [comment]
Note that even if the signing is fixed using all the changes above it fails part of the validation:
```
> codesign -vvv ./MailClient.Mobile.iOS.app
./MailClient.Mobile.iOS.app: valid on disk
./MailClient.Mobile.iOS.app: does not satisfy its designated Requirement

designated => identifier "com.xamarin.Xamarin-PreBuilt" and anchor apple generic and certificate leaf[subject.CN] = "Apple Development: vsx Extensibility (MRQ5M4P6SM)" and certificate 1[field.1.2.840.113635.100.6.2.1] /* exists */
```
This does not prevent it from running on device though.

**Comment by filipnavara** [comment]
So, there are actually more bugs that I keep running into... since parts of the code are only executed for frameworks and not for the main app they may not be readily apparent.

Counting of code slot hashes uses [incorrect boundary limit](https://github.com/apple-opensource/Security/blob/a070b704ca4d37793326cdc9be14fe157fde602b/OSX/libsecurity_codesigning/lib/cdbuilder.cpp#L293-L307). It's also called with `numberOfHashesToUpdate == 2` on two call sites which doesn't guarantee that the whole loader section, which is modified, is properly rehashed.

Let's fix the hashing boundary first:
```csharp
        public void UpdateCodeSlotHashes(MachO machO, int numberOfHashesToUpdate = -1)
        {
            uint numberOfHashesToUpdateLocal = numberOfHashesToUpdate == -1 ? this.NumberOfCodeSlots : (uint)numberOfHashesToUpdate;
            long remaining = this.CodeLimit64 != 0 ? this.CodeLimit64 : this.CodeLimit;
            byte[] rawMachO = machO.GetRawMachO();
            for (uint index = 0; index < numberOfHashesToUpdateLocal; ++index)
            {
                int pageSize = remaining > 4096 ? 4096 : (int)remaining;
                this.Hashes[index] = this.HashAlgorithm.ComputeHash(rawMachO, (int)index * 4096, pageSize);
                remaining -= pageSize;
            }
        }
```

Now the callers should actually use either `-1` to recompute all the hashes or derive the necessary number of pages from `MachO.SizeOfLoadCommands` (ie. round it up the the number of pages and recalculate that).

The two bugs usually, but not always, cancel each other out. Since only two page hashes are recalculated the last hash in code directory is not overwritten with incorrect value. Frameworks usually don't have too many segments and load commands that rehashing the first two pages works out. However, even the main executable from the bundle needs at least 4 pages to be rehashed. Again, this is cancelled out due to `forceSignAppExecutable` never set to `true` in `Signer.Resign` calls.

**Comment by filipnavara** [comment]
Hopefully the last one :-)

Since iOS ~14.7 the Hot Restart failed to load frameworks like SkiaSharp. It silently crashed with SIGKILL due to protection violation and later crashed after ~20 seconds with SIGSEGV and bogus messages.

This is caused by incorrect value set in the `ExecSegFlags` (`Executable Segment flags`) field in the Code Directory header of the resigned framework binaries.

Naive fix in `CodeDirectory.EmitBlobForExecutable`:
```csharp
                if (directoryVersion >= CodeDirectoryVersion.XNU_iOS11)
                {
                    Segment segment = ...;
                    writer.WriteInt64(0L);
                    writer.WriteInt64(segment.Size);
                    if (numberOfSpecialSlots >= 5) // Application (5+ slots)
                        writer.WriteInt64(17L);
                    else // Framework (3 slots)
                        writer.WriteInt64(0);
                }
```

**Comment by dalexsoto** [comment]
Hello @filipnavara!

What a wonderful investigation, really thanks a lot I have passed this information to the appropriate teams and they will be working on it. I'll keep the bug open and will update as progress is being made. 

Again thank you and we owe you another one!

**Comment by emaf** [comment]
@filipnavara This is an awesome investigation! Thank you so much for sharing all these information with us, it helps a lot!

**Comment by filipnavara** [comment]
I hope it helps. I've locally also updated the tool to remove BouncyCastle (and use `CmsSigner`/`SignedCms` from System.Security.Cryptography.Pkcs) and use updated ELFSharp sources (mainly missing this bug fix: https://github.com/konrad-kruczynski/elfsharp/commit/4eb70ce437fd787804750b0ddc218045d683162b) so if you ever decide to open source it I'll be happy to submit pull requests.

**Comment by MaximMikhisor** [comment]
Do you have any update for this issue?
Will Hot Restart work?

**Comment by filipnavara** [comment]
> Do you have any update for this issue? Will Hot Restart work?

Most of the issues were fixed upstream and already released with a Visual Studio update. I'll close the issue.

**Comment by dotMorten** [comment]
With the latest VS17.2 preview 2.1 I'm still seeing my framework files not being deployed with hot restart. The moment I make an interop call into the framework file, it goes boom. Looking at the stuff put in the .api in `%TEMP%\Xamarin\HotRestart\Signing\MyAppName.app\out\MyAppName.ipa` I don't see the frameworks in there either.
Same app deployed with a remote build host works just fine.

**Comment by MaximMikhisor** [comment]
I have VS 2019 16.11.11 and iOS 15 device.
Cannot use Hot Restart.
Have Deploy Error: 
Could not install the application 'C:\Users\maxim\AppData\Local\Temp\Xamarin\HotRestart\Signing\XXX.app\out\XXX.ipa' on the device Spinoza 12. Details: ApplicationVerificationFailed(3892346901) - Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.G2Nh62/extracted/Payload/XXX.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)

Though do not know is this bug related to current issue or not.
