### ISSUE TITLE
svg.skia / linker error on device builds

### ISSUE THREAD

**Issue by vogtadi** [xamarin/xamarin-macios#13634]
### Steps to Reproduce

1. Project with svg.skia 0.5.10 (NuGet)
2. Build for hardware target (Note: Problem is not visible for building for Simulator Targets)

### Expected Behavior
Build and Deploy

### Actual Behavior
Linker Error: see below (native linking failed)

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.16 (build 2)
Installation UUID: 8d1481ff-adae-41a8-938c-f0b574ea8037
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/x64/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.1
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 21:09:18 UTC

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Version: 8.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/handycash/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810160002
Git revision: 6dbc7886fa608147f685a7df3912249400c84716
Build date: 2021-12-14 15:54:37-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.1.0
Darwin 21.2.0 Darwin Kernel Version 21.2.0
    Sun Nov 28 20:29:10 PST 2021
    root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 x86_64

=== Enabled user installed extensions ===

Stack Overflow Search 0.7.1


```

### Build Logs
/REDACTED/iOS/MTOUCH: Error MT5216: Native linking failed for '/REDACTED/iOS/obj/iPhone/Debug/device-builds/iphone14.2-15.2/mtouch-cache/arm64/libSvg.Custom.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT5216) (REDACTED.AppId)

### Example Project (If Possible)
Not available.

**Comment by rachelkang** [comment]
Hi, @vogtadi - thank you for your feedback and happy holidays! Please provide [full build logs](https://docs.microsoft.com/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2022#save-a-binary-log) and if possible, a sample project reproducing this issue, so that we can investigate further.

**Comment by vogtadi** [comment]
Thanks for getting back - it took me quite some time to setup a working, minimalistic project and then there was the holidays 🙂.

Finally managed to reproduce it cleanly. (Sample Project at https://github.com/vogtadi/svg.skia.bug.13634)

Steps to Create the Issue
1. Library Project with netstandard2.0 and a reference to Svg.Skia
2. Some code referencing this library, i.e. a small SVGToPNG converter function.
3. A Xamarin.iOS Project with a reference to this Library Project and a code reference to the converter function
4. Xamarion.iOS IncrementalBuild Option Enabled **THIS IS THE TRIGGER**
5. Build for iPhone -> fails with mentioned error
6. Xamarion.iOS IncrementalBuild Option Disabled
7. Build for iPhone -> works 🙂 

In order you don't have to recreate the project structure, please refer to https://github.com/vogtadi/svg.skia.bug.13634 for a sample project demonstrating the issue.

Regards
Adrian

**Comment by rolfbjarne** [comment]
> Xamarion.iOS IncrementalBuild Option Enabled THIS IS THE TRIGGER

This is fixed in .NET (the incremental build option has been superseded with a new method of making builds faster, which doesn't have the same problems as the incremental build option did).

**Comment by vogtadi** [comment]
> > Xamarion.iOS IncrementalBuild Option Enabled THIS IS THE TRIGGER
> 
> This is fixed in .NET (the incremental build option has been superseded with a new method of making builds faster, which doesn't have the same problems as the incremental build option did).

Nope, its not fixed. I run into the same problem. Xamarion.iOS IncrementalBuild needs to remain disabled.

<pre>
Visual Studio Community 2022 for Mac
Version 17.3.7 (build 11)
Installation UUID: f4c9d2ef-c783-4736-9d0d-c940ab8586e0

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.2.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.402/Sdks
SDK Versions:
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.103
	6.0.102
	6.0.101
	5.0.408
	5.0.406
	5.0.405
	5.0.404
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.417
	3.1.416

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	5.0.17
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.0.1 (21336)
Build 14A400

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-10-05 17:22:59 UTC

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/handycash/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-10-05 17:23:04 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-10-05 17:23:04 UTC

Build Information
Release ID: 1703070011
Git revision: b625496a1b9780a50e1935e641beecf8979c795b
Build date: 2022-10-05 17:21:01+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:19:52 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

</pre>

**Comment by rolfbjarne** [comment]
Can you provide a binlog (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) of that shows the failure?
