### ISSUE TITLE
Improve default Mac Catalyst build times on arm64 

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#21444]
The default build times for a Mac Catalyst app on arm64 is horrendous:

* `dotnet new maccatalyst && dotnet build`: 1 minute
* `dotnet new maccatalyst && dotnet build /p:UseInterpreter`: 17 seconds
* `dotnet new maccatalyst && dotnet build /p:TrimMode=partial`: 12 seconds
* `dotnet new maccatalyst && dotnet build /p:TrimMode=full`: 12 seconds

I suggest we enable the trimmer by default for Debug mode on Mac Catalyst in order to improve this.

**Comment by tipa** [comment]
In tests with my real-world apps, build + deploy times to the simulator are ~16 seconds when only specifying `UseInterpreter` and ~13-14 seconds when specifying both `UseInterpreter` & `TrimMode=partial`. Will this change yield similar results? I am asking because in the commit it says

> Linking is on by default in the simulator when building for arm64, **as long as the interpreter is not enabled**

https://github.com/xamarin/xamarin-macios/blob/bc1ae55783c0e0ceb419e9b103b2b09201b9faf8/dotnet/targets/Xamarin.Shared.Sdk.Trimming.props#L57C1-L58C1

**Comment by rolfbjarne** [comment]
> In tests with my real-world apps, build + deploy times to the simulator are ~16 seconds when only specifying `UseInterpreter` and ~13-14 seconds when specifying both `UseInterpreter` & `TrimMode=partial`. Will this change yield similar results? I am asking because in the commit it says
> 
> > Linking is on by default in the simulator when building for arm64, **as long as the interpreter is not enabled**
> 
> [`bc1ae55`/dotnet/targets/Xamarin.Shared.Sdk.Trimming.props#L57C1-L58C1](https://github.com/xamarin/xamarin-macios/blob/bc1ae55783c0e0ceb419e9b103b2b09201b9faf8/dotnet/targets/Xamarin.Shared.Sdk.Trimming.props#L57C1-L58C1)

Yes, you should get some similar results (probably somewhere between 13 and 16 seconds).

It should be easy enough for you to try it, by building with "TrimMode=partial" (without setting UseInterpreter).

**Comment by tipa** [comment]
Only tested with one app, but the build & deploy time to simulator increased from 16 seconds to 21 seconds when removing `UseInterpreter=false` and using `TrimMode=partial` only

**Comment by jeremy-visionaid** [comment]
I've found that build times are greatly improved since https://github.com/dotnet/runtime/issues/110406 was closed with the release of SDK 9.0.203

**Comment by rolfbjarne** [comment]
This has been fixed.

**Comment by tipa** [comment]
In my small, NativeAOT compiled app, I still get much worse build times in net10-rc2.

No flags: 21 secs after change to app launch in simulator
`UseInterpreter=true`, `TrimMode=partial`:  11 seconds

**Comment by rolfbjarne** [comment]
@tipa what's your numbers if you enable either the interpreter, or the trimmer (but not both)?

**Comment by tipa** [comment]
I did the tests again today:

default: 20-21 sec
`TrimMode=partial`: 20-21 sec
`UseInterpreter=true`:  11-12 sec
`UseInterpreter=true` & `TrimMode=partial`: 11-12 sec

**Comment by rolfbjarne** [comment]
OK, so it looks like enabling the interpreter is what makes it fastest, doesn't matter the trim mode.

At this point it's too late to fix anything in .NET 10 (also there's no easy fix here besides enabling the interpreter, which has other side effects), but the good news is that we have some plans and we hope to improve this a lot in .NET 11 :)

**Comment by tipa** [comment]
Following up with a minimal iOS simulator repro comparing .NET 10 and .NET 11 RC1.

Median build times over three iterations:

| Configuration | Unchanged | After edit |
|---|---:|---:|
| .NET 10: `UseInterpreter=true`, `TrimMode=copy` | 0.69 s | 3.24 s |
| .NET 11 RC1: untouched Debug defaults | 6.89 s | 8.63 s |
| .NET 11 RC1: `Registrar=partial-static`, `PublishReadyToRun=false` | 0.36 s | 4.49 s |

The .NET 11 default case has no Debug property overrides—not even TrimMode=copy. Explicitly setting that property changes the trimming pipeline in RC1, so it's excluded from the default baseline.

On an unchanged default build, assembly preparation alone took 6.40 s; compilation and ILLink were skipped.

#26409 acknowledges extra processing on incremental Debug builds and raises retaining the cheaper registrar. Could that become the Debug default?

Minimal repro attached: two projects and a runner with instructions. To test .NET 11 defaults, remove its Debug PropertyGroup.

Environment: Apple M5, Xcode 26.6, Debug, iossimulator-arm64. Restore happens before timing; signing and deployment are excluded.

[ios-build-times.zip](https://github.com/user-attachments/files/32025610/ios-build-times.zip)

**Comment by rolfbjarne** [comment]
> [#26409](https://github.com/dotnet/macios/pull/26409) acknowledges extra processing on incremental Debug builds and raises retaining the cheaper registrar. Could that become the Debug default?

The `partial-static` registrar will become the default for untrimmed builds in RC2: https://github.com/dotnet/macios/pull/26556, so the last row of numbers is the closest to the final numbers. I'm also looking into a few more improvements for the "After edit" scenario, hopefully getting it within a couple of seconds. In particular `PublishReadyToRun=false` shouldn't make a difference, because ReadyToRun shouldn't be happening for edits in user code.
