### ISSUE TITLE
Getting the error MT3001: Could not AOT the assembly

### ISSUE THREAD

**Issue by sharmashiv** [xamarin/xamarin-macios#4012]
/Users/macmini01/Desktop/Per/RunningCode_Both/XXX_Mobile Sourcecode_2Apr2018/XXX/XXX.iOS/MTOUCH: Error MT3001: Could not AOT the assembly '/Users/macmini01/Desktop/Per/RunningCode_Both/XXX_Mobile Sourcecode_2Apr2018/XXX/XXX.iOS/obj/iPhone/Debug/mtouch-cache/64/Build/OsmSharp.UI.dll' (MT3001) (XXX.iOS). This error occurred when trying to build for physical iOS device, but not for simulator.

**Comment by VincentDondain** [comment]
Hi, this sounds like it's the same issue as https://github.com/xamarin/xamarin-macios/issues/3199.

A fix was deployed for our 15.7 release (currently in alpha/beta see https://developer.xamarin.com/releases/ios/xamarin.ios_11/xamarin.ios_11.10/#Issues_Fixed).

In any case please include your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by sharmashiv** [comment]
[BuildLog.txt](https://github.com/xamarin/xamarin-macios/files/1963808/BuildLog.txt)
![screen shot 2018-05-01 at 5 07 22 am](https://user-images.githubusercontent.com/12165887/39473649-b58b9e26-4d04-11e8-83ec-300785a104a0.png)

Two cases in build(xamarin.ios):

1) When build option setting:

Linker behavior: Link All
In that case application crash with this error message
You MUST invoke LoadApplication () before calling base.FinishedLaunching ()

2) When build option setting:

Linker behavior: Link Framework SDKs Only
I'm getting the error:

MT3001: Could not AOT the assembly.

/Users/macmini01/Desktop/Per/RunningCode_Both/XXX_Mobile Sourcecode_2Apr2018/XXX/XXX.iOS/MTOUCH: Error MT3001: Could not AOT the assembly '/Users/macmini01/Desktop/Per/RunningCode_Both/XXX_Mobile Sourcecode_2Apr2018/XXX/XXX.iOS/obj/iPhone/Debug/mtouch-cache/64/Build/OsmSharp.UI.dll' (MT3001) (XXX.iOS

https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#MT3001

**Comment by sharmashiv** [comment]
[Build_Log.txt](https://github.com/xamarin/xamarin-macios/files/1966037/Build_Log.txt)
[Xamarin_IDE_Log.txt](https://github.com/xamarin/xamarin-macios/files/1966038/Xamarin_IDE_Log.txt)

**Comment by sharmashiv** [comment]
**When build option setting:
Linker behavior: Link All**
[Carsh Log .txt](https://github.com/xamarin/xamarin-macios/files/1966063/Carsh.Log.txt)
[Xamarin_IDE_Log.txt](https://github.com/xamarin/xamarin-macios/files/1966064/Xamarin_IDE_Log.txt)

**When build option setting:
Linker behavior: Link Framework SDKs Only**
[Build_Log.txt](https://github.com/xamarin/xamarin-macios/files/1966067/Build_Log.txt)
[Xamarin_IDE_Log.txt](https://github.com/xamarin/xamarin-macios/files/1966068/Xamarin_IDE_Log.txt)

**Comment by sharmashiv** [comment]
@VincentDondain  Any update, i am really frustrated with Xamarin development.

**Comment by VincentDondain** [comment]
I see `* Assertion at /Users/builder/data/lanes/5909/f62de472/source/xamarin-macios/external/mono/mono/mini/aot-compiler.c:6320, condition 'p - buf < buf_size' not met` in your `mtouch` logs that leads to a crash and no output from the AOT compiler and then the MT3001 error.

I'm trying to find if this is a known issue but in any case we'll need your **version informations** (see how to get that in my first comment) to confirm your environment.

I'd be great to have the `OsmSharp.UI.dll` too.

**Comment by VincentDondain** [comment]
I believe your issue is similar to https://github.com/mono/mono/issues/7637. Your version informations will help us know if you have that patch already or not.

**Comment by VincentDondain** [comment]
Ah ok, then yes we believe this was fixed in a later version of Xamarin.iOS. The mono issue I mentioned above has a `2017-12 (5.10.xx)` milestone and that mono 2017-12 was bump with Xamarin.iOS 11.10.XX series.

@sharmashiv could you please try your test case with the beta version of Xamarin.iOS (currently 11.10.1.174) and let us know if you still get the MT3001 error.

_Note: If you do still have an issue we'll need at least the faulty dll to investigate more._

**Comment by sharmashiv** [comment]
@VincentDondain @alanjclark  Please share beta version URL.

**Comment by alanjclark** [comment]
@sharmashiv I did notice that your IDE is significantly out of date.  Xamarin Studio is now Visual Studio for Mac (as part of its natural evolution).  There has not been an update for Xamarin Studio in over a year.

The _easiest_ way to get the Beta (and the method I would recommend by far) is to update to [Visual Studio for Mac](https://www.visualstudio.com/vs/mac/).  There was a dialogue box prompting to update the IDE in the latest Xamarin Studio, but you may have suppressed this.  You can use the link above.

If you wish to continue with Xamarin Studio then please email me for a link (I would prefer not to publicly publish links to releases that will be legacy after the next release).  However, please note that this is _not_ a scenario we would be able to support given the age of the IDE you are using and the date the last update was published.

**Comment by sharmashiv** [comment]
@VincentDondain  @alanjclark  Thanks guys now its fixed partial.


Two cases in build(xamarin.ios):

_1. When build option setting:
Linker behavior: Link All
In that case application crash with this error message
You MUST invoke LoadApplication () before calling base.FinishedLaunching ()_



**2. When build option setting:
Linker behavior: Link Framework SDKs Only
I'm getting the error:

MT3001: Could not AOT the assembly.

/Users/macmini01/Desktop/Per/RunningCode_Both/XXX_Mobile Sourcecode_2Apr2018/XXX/XXX.iOS/MTOUCH: Error MT3001: Could not AOT the assembly '/Users/macmini01/Desktop/Per/RunningCode_Both/XXX_Mobile Sourcecode_2Apr2018/XXX/XXX.iOS/obj/iPhone/Debug/mtouch-cache/64/Build/OsmSharp.UI.dll' (MT3001) (XXX.iOS**

**Comment by VincentDondain** [comment]
Hi,

Glad the MT3001 error is fixed for you.

Now please let's keep **1 GitHub issue per reported problem**. This issue (#4012) was about the MT3001 error that is now fixed so I will close it.

You're then having a 2nd issue where your app crash with `You MUST invoke LoadApplication () before calling base.FinishedLaunching ()` and I believe this is a Xamarin.Forms issue/question. Please open a new issue here https://github.com/xamarin/Xamarin.Forms/issues/new.

I think you will have to provide more information because you might be doing something wrong in your `AppDelegate.cs` (a test case is always ideal for us to help you) and also the stack trace you gave us is not symbolicated (not giving us much info).

See https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/symbolicate-ios-crash and https://jmillerdev.net/symbolicating-ios-crash-files-xamarin-ios/ for how to symbolicate.

**Comment by TomQv** [comment]
With vs2019 this exact error is back:
"Could not AOT the assembly '/Users/..../obj/iPhone/Debug/mtouch-cache/64/3-Build/OsmSharp.dll'"
Same project, same settings was fine with vs2018...  :(

**Comment by dktechindia** [comment]
I am getting this issue with Visual Studio Community 2019 (Version 16.1.5) and MacOS Catalina (Version 10.15 Beta (19A501i)

Any workaround for this?

**Comment by rolfbjarne** [comment]
@dktechindia the MT3001 error can have many causes, please file a new issue and attach your complete build log, and we'll have a look to see if it's the same case or not, and if something can be done.

**Comment by dktechindia** [comment]
**Here is full log**
[log.txt](https://github.com/xamarin/xamarin-macios/files/3360711/log.txt)

**here is IDE detail**
_Microsoft Visual Studio Community 2019
Version 16.1.5
VisualStudio.16.Release/16.1.5+29025.244
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA114
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   16.1.429.50124
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.1.429.50124
Azure Functions and Web Jobs Tools

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

GitLab Extension for Visual Studio   1.0.189
A Visual Studio Extension that brings the GitLab Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.10424.1 Commit Hash:c3ce0ae0b29c0b3a755ffc12f8a685fe7ddd3600
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.28917
Visual C++ for Linux Development

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26


Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support._

**Comment by dktechindia** [comment]
one thing I noticed, it is showing path /Users/<my user name>/Library/<and so on> but in my mac Library folder is not under Users folder. It is on the same level as Users folder. How can I correct this ? I think if I can change this path, it should work correctly.

**Comment by AndreasGassmann** [comment]
@dktechindia I'm facing the same issue. Were you able to resolve it or did you open another issue?

**Comment by k16blfurm** [comment]
Same, I'm currently having this issue rn.

**Comment by se** [comment]
I'm also facing the same issue with WatchOsApp. Is there any luck guys?

**Comment by dktechindia** [comment]
> @dktechindia I'm facing the same issue. Were you able to resolve it or did you open another issue?

No. I just reverted back to Mojave and everything is working fine now. Xamarin team have to fix it for Catalina.

**Comment by dmcspadden** [comment]
Same issue here - trying to avoid reverting back to Mojave since Catalina was working.  Any update from the xamarin team?

**Comment by se** [comment]
> Same issue here - trying to avoid reverting back to Mojave since Catalina was working. Any update from the xamarin team?

I got an answer like this https://github.com/xamarin/xamarin-macios/issues/6566#issuecomment-519638373. You can check it out.

**Comment by Uncommon** [comment]
I just started getting this error after updating to VS 8.2.4.

**Comment by MarMarIV** [comment]
Still same issue on macOS Catalina 10.15 Beta, any solution? I'm affraid to upgrade second MAC with Mojave...

**Comment by aroyzen1983** [comment]
Also running into similar issue, did anyone find a work around?

**Comment by VincentDondain** [comment]
To anyone getting this issue recently: the MT3001 error can have many causes, please file a new issue and attach your complete diagnostic level build log (ideally a test case) as well as your version informations, and we'll have a look to see if it's the same case or not, and if something can be done.
