### ISSUE TITLE
Can't open Storyboard file in iOS Designer when check the safe area layout guides

### ISSUE THREAD

**Issue by aixiaozi** [xamarin/xamarin-macios#4340]
### Problem Statement
When the customer check the safe area layout guides in his storyboard file, customer unable open the storyboard file in iOS designer. 

![safe](https://user-images.githubusercontent.com/18043540/41916072-cbb8c46a-7989-11e8-9c58-d9203b6ca4b6.PNG)

![mac_vs](https://user-images.githubusercontent.com/18043540/41916099-dcfb1af2-7989-11e8-80d1-baf6d4adcf72.PNG)

But if customer uncheck the safe area layout guides it is working fine.

Everything works fine when the customer use the older version of VS 7.5.0 for Mac and XCode 9.3, but when I help them installed the older version of VS for Mac and XCode, the issue still persists.

### Steps to Reproduce

1.  Copy customer's storyboard to a blank project, open this storyboard, everything works fine because it didn't check the safe area layout guides.

2. Uncheck the safe area layout guides, close customer's storyboard and open again, the issue happened.

- When the customer creats a blank Xamarin.iOS project, can't reproduce this issue.
- When the customer creates a blank Storyboard in this project, also can't reproduce this issue.

### Expected Behavior
Could open the Storyboard like this:

![fine](https://user-images.githubusercontent.com/18043540/41915488-6becf228-7988-11e8-8701-9eec707be93a.PNG)

### Actual Behavior

![mac_vs](https://user-images.githubusercontent.com/18043540/41913497-0d83f2fe-7983-11e8-9ed4-5af89d1624b8.PNG)

### Environment

```
Visual Studio Community 2017 for Mac
Version 7.5.3 (build 7)

Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Community)

Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.4.1 (14161)
Build 9F2000

Xamarin.Mac
Version: 4.4.1.193 (Visual Studio Community)

Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

Xamarin.Android
Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/manjunath/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 705030007
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
  
Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.5

```

### Build Logs

[StoryBoardErrorLogs_1.txt](https://github.com/xamarin/xamarin-macios/files/2137203/StoryBoardErrorLogs_1.txt)
[StoryBoardErrorLogs_2.txt](https://github.com/xamarin/xamarin-macios/files/2137204/StoryBoardErrorLogs_2.txt)

### Example Project (If Possible)

Customer has concern about this, so I could only share with you the issue Storyboard via email.

> VS bug [#638594](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638594)

**Comment by aixiaozi** [comment]
Have shared the issue storyboard via email. :)

**Comment by aixiaozi** [comment]
@viniciusjarina , is there any updates about this issue?

**Comment by aixiaozi** [comment]
@viniciusjarina , can you reproduce this issue? If so, is there any workaround?

**Comment by aixiaozi** [comment]
@chkn thx a lot!

**Comment by alanmcgovern** [comment]
The kind of problem that causes this issue has been resolved and we've added some user visible warning messages when mismatches occur. This will allow people to detect and resolve the problem themselves in future. The additional informational feature will ship in a future release and the bug which caused the problem in the first place has been resolved in 15.8.

Thanks for the report!

**Comment by manjunathaVadhiraaju** [comment]
Still  Issue persists in latest visual studio and Xcode 10
problem in rendering storyboard file in iOS Designer.

=== Visual Studio Community 2017 for Mac ===

Version 7.6.8 (build 38)
Installation UUID: 56c55974-b747-4502-b0f1-526429432dbc
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/manjunatha/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706080038
Git revision: f4178f550a4de7c03aa23678041abe4fc388cf72
Build date: 2018-09-28 14:21:41+00
Build branch: release-7.6
Xamarin extensions: 051b653186a95ced1c127dfd8c358df1b9315d0d

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by alanmcgovern** [comment]
Can you share a storyboard which reproduces the problem? The issue we addressed did not occur in the 7.6 release so the patch we created was not included in that particular release.

**Comment by manjunathaVadhiraaju** [comment]
[YourdrsStoryboard.storyboard.zip](https://github.com/xamarin/xamarin-macios/files/2449119/YourdrsStoryboard.storyboard.zip)

**Comment by viniciusjarina** [comment]
Hello @manjunathaVadhiraaju 

Sorry to hear that the problem is still happening for you. I've downloaded your storyboard and tried to open with the same version of VS4M you have `Version 7.6.8 (build 38)` and enabled the `Safe Area Layout`.

Unfortunately, I can't repro the issue 😕

![ygrcjrsvqi](https://user-images.githubusercontent.com/926868/46546424-038d2a00-c897-11e8-8e3f-a77ac82182e4.gif)

**Comment by aixiaozi** [comment]
@viniciusjarina Hi, @manjunathaVadhiraaju has resolved this issue by reinstalled VS and Xcode 10.

**Comment by alanmcgovern** [comment]
Great! We'll close this issue again. Please do reopen if you have further issues!

**Comment by KIzotov** [comment]
I have a similar problem
For: Visual Studio Professional 2017 for Mac
Version 7.6.11 (build 9)
Installation UUID: 8c093965-9c85-434e-8310-de5be366a839
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.3
	2.1.2
	2.1.1
	2.0.6
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.0.0.0 (Visual Studio Professional)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

Xamarin.iOS
Version: 12.1.0.15 (Visual Studio Professional)
Hash: cbfb047a
Branch: xcode10.1
Build date: 2018-10-30 22:57:23-0400

Xamarin.Android
Not Installed

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

Operating System
Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

**Comment by alanmcgovern** [comment]
Can you share a project, or possibly just the storyboard, with us so we can diagnose the issue. We can organise a private way to do that if you can’t share the file publicly.

A copy of the log files from a session where you triggered the issue would also be helpful!

**Comment by KIzotov** [comment]
With Xcode 9 works
I’m not able to upload a storyboard
Problem with Xcode 10 and Xcode 10.1

**Comment by alanmcgovern** [comment]
We will need more information to be able to diagnose the issue. At the least we'll need the logs to know where to start looking.

Thanks!
