### ISSUE TITLE
[Xcode10]Two Simulators are launching while deploying an iOS App with Xcode10-beta3

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4421]
### Steps to Reproduce

1.  Install Xamarin.iOS 11.99.1.44, Xcode10-beta3 (10L201y)
2. Create an iOS app 
3. Build and deploy it on simulator eg: iPhoneX iOS 12.0

### Expected Behavior
App builds, deploys and launch on iPhoneX iOS 12.0
### Actual Behavior
App builds, deploys and launch on iPhoneX iOS 12.0. But a second simulator also opens iPhone4S 9.3.5
### Environment

```
https://gist.github.com/GouriKumari/eeff3d2252cc2a2baddccacaeb14a76a
```

### Build Logs

Screenshot: https://screencast.com/t/aH3UvYDYzI1V

> VS bug [#669811](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669811), VS bug [#680549](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/680549), VS bug [#713315](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/713315)

**Comment by VincentDondain** [comment]
I have the same issue and filed 
https://github.com/xamarin/xamarin-macios/issues/4531 (dupe).

Video of the issue: https://www.dropbox.com/s/s1azhk66c4r6r7e/DualSim.mov?dl=0

**Comment by rolfbjarne** [comment]
One simulator (the wrong one) launches before mlaunch is called (which can easily be demonstrated by adding a `sleep 20` in `/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch` like this: https://gist.github.com/rolfbjarne/2577d73d53c41b34d8dd7bcdb690e4a0#file-mlaunch-L8-L10 - if the simulator launches before the mlaunch script stops sleeping, this can't be a bug in XI).

**Comment by VincentDondain** [comment]
Yea so the `MakeSimulatorGrabFocus` was causing this is called before / at the same time as mlaunch. There are other calls to `MakeSimulatorGrabFocus` later on in the deployment process that are fine.

**Comment by VincentDondain** [comment]
Fixed in https://github.com/xamarin/md-addins/pull/3484 and https://github.com/xamarin/md-addins/pull/3488.

**Comment by VincentDondain** [comment]
Backported in https://github.com/xamarin/md-addins/pull/3492.

Also it can happen on VSMac stable and when using stable Xcode **if you installed a Xcode beta**.

At this point you’d have the _Simulator (beta)_ installed as well as the _non beta Simulator_ application. The AppleScript we’re using to grab focus then calls “Simulator” but that can result in the beta simulator app being called and brought forward.

Therefore my fix, which removes that early call to the simulator app (and only brings to front the currently running simulator app) solves this.

cc @slluis and @Aguilex to back port this into the next SR. I don't know which branch to use.

**Comment by GouriKumari** [comment]
Verified with VSFMac 7.6.1.7 and the issue is resolved.

Screenshot: https://screencast.com/t/067SEo7uU

Test Env:
https://gist.github.com/GouriKumari/6c601db46d57c223f82caef0ba3db996

**Comment by LeGiangAnh** [comment]
@GouriKumari I'd like to contact you. Could you please email me anh.legiang (at) gmail.com or https://twitter.com/LeGiangAnh?

**Comment by awattar** [comment]
It's still present in stable channel when using latest VS and XCode

Visual Studio Enterprise 2017 for Mac
Version 7.6.9 (build 22)

Apple Developer Tools
Xcode 10.0 (14320.25)
Build 10A255

Xamarin.iOS
Version: 12.0.0.15 (Visual Studio Enterprise)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

**Comment by VincentDondain** [comment]
Hi @awattar,

With the environment you have, the double simulator issue should be fixed.

Could you upload a screencast while reproducing the issue so I can see what's happening?

Please note that **you will still be able to have multiple simulators at the same time** with that fix. The issue was that if you ran on a given simulator (iPhone X), closed the simulator app and launched an other simulator (iPhone Xs), because of the grab focus code in the IDE we'd grab focus on the simulator app too early preventing its reset, therefore showing you 2 simulator.

If you **close** the simulator app now, and launch on any simulator, with VSMac 7.6.9 (build 22) you should only have 1 simulator that opens. If the simulator app is still **open** we'll start additional simulators.

**Comment by awattar** [comment]
Hi @VincentDondain 
Thanks for the detailed explanation.

This is my scenario:
1. Launch VS.
2. Run app on simulator A.
3. Close simulator app.
4. Switch configuration - for example from Debug to Release.
5. Run app on simulator B.

It launches two simulators A and then B. Is this behaviour that you describe or something new?

**Comment by awattar** [comment]
Now I'm even able to reproduce it without changing anything - starting from cold start on XF project from template.

[https://streamable.com/b1lzw](url)

**Comment by VincentDondain** [comment]
Ah... I can reproduce now. This has to do with the release configuration (only). We might need to remove another `GrabFocus` here. Thanks for the report, this has not been reported before I believe. We'll fix it.

**Comment by awattar** [comment]
No problem. Glad I was able to help.

**Comment by VincentDondain** [comment]
Alright I fixed it for the release mode too now (:

I'll make sure it's included in the next release, thanks @awattar for the feedback.

**Comment by VincentDondain** [comment]
VSMac PR has been merged, it will be included in the next major release.
