### ISSUE TITLE
On Demand Resource asset packs not accessible on Visual Studio 8.4

### ISSUE THREAD

**Issue by btourtellott** [xamarin/xamarin-macios#8026]
### Steps to Reproduce

1. Create a Xamarin.iOS application that uses On-Demand Resource asset packs with Visual Studio version 8.4 or higher.
2. Launch the application with Visual Studio using an iOS simulator
3. During application runtime, attempt to access an asset pack
4. Observe asset pack cannot be found

### Expected Behavior
After defining resources as "BundledResources" with an On Demand Resource tag, I should be able to access the asset packs created during application runtime using an iOS simulator. When using Visual Studio version 8.4 or higher and trying to access those asset packs, the following is logged:
`[general] Begin: Request 0x0x600000e7db90 response: Error: Error Domain=NSCocoaErrorDomain Code=4994 "The requested application data doesn’t exist." UserInfo={NSLocalizedFailureReason=InvalidTag}`

When using Visual Studio 8.3 with an iOS simulator, the line is not logged, and the asset packs are accessible as expected. When using Visual Studio 8.4 or higher with a real device (not iOS simulator), the line is not logged, and the asset packs are accessible as expected.

### Actual Behavior
On Demand Resource asset packs should be accessible on an iOS simulator using Visual Studio 8.4 or higher

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.4.1 (build 4)
Installation UUID: 971f1457-2029-4736-a992-93e3cea4fedd
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.0.1
	3.0.0
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.0.5

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/btourtellott/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/btourtellott/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-08 19:54:56 UTC

=== Android Device Manager ===

Version: 16.4.0.28
Hash: 68e9956
Branch: remotes/origin/d16-4
Build date: 2020-01-08 19:55:18 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin Designer ===

Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Build Information ===

Release ID: 804010004
Git revision: 5f675128315bd5886b283aa192b334a02bc8a758
Build date: 2020-01-10 13:54:46+00
Build branch: release-8.4
Xamarin extensions: 6e5c119bf1e7b092680c1491be659f152329f74e

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Sun Dec  1 18:59:03 PST 2019
    root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64


```

### Build Logs

Relevant from the build log. Subbed out project name for "XXX", but the project name is correct:
```
Target "_CreateAssetPackManifest" in file "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets":
  Using "CreateAssetPackManifest" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Tasks.dll".
  Task "CreateAssetPackManifest"
  Done executing task "CreateAssetPackManifest".
Done building target "_CreateAssetPackManifest" in project "XXX".
```

### Example Project (If Possible)
Can use this as an example project: https://github.com/xamarin/ios-samples/tree/master/ios9/iTravel

> VS bug [#1076475](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1076475), VS bug [#1081877](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1081877)

**Comment by chamons** [comment]
Thanks for the report. This issue could lay in multiple places, but let's start with the IDE.

**Comment by alekseevabah** [comment]
Same for us, but building from Windows Visual Studio.
Looks like the asset packs are generated (can find them in bin/OnDemandResources), but not packaged to simulator .app package.

**Comment by olegoid** [comment]
I attempted to reproduce the problem using various build environments and the sample (iTravel) referenced in the bug description.

Here's what I tried:
1) VSfM 8.3/Xamarin.iOS 13.18.0.23/Xcode 11.4
2) VSfM 8.4/Xamarin.iOS 13.18.0.23/Xcode 11.4
3) VSfM 8.5/Xamarin.iOS 13.18.0.23/Xcode 11.4

4) VSfM 8.4/Xamarin.iOS 13.10.0.17/Xcode 11.4
5) VSfM 8.4/Xamarin.iOS 13.10.0.17/Xcode 11.3.1

Still, can't reproduce the bug in any of the above environments.

There's a chance that it's an upstream issue that showed up after Xcode upgrade (based on this Apple forum discussion: https://forums.developer.apple.com/thread/43202)

**Comment by chamons** [comment]
@Sebastian1989101 @alekseevabah @btourtellott - @olegoid just tried to reproduce this issue and has failed. C

ould someone please revalidate and provide steps for us to reproduce?

**Comment by alekseevabah** [comment]
We had the issue too on windows VS 16.5.1 and XCode 11.3, but after update to VS 16.5.4 and XCode 11.4.1 it works now.

**Comment by chamons** [comment]
Given the inability to reproduce on our end and reports that it is fixed, i'm going to close for now. Reporter - please reopen with details if you are still hitting this.

**Comment by Sebastian1989101** [comment]
@chamons This issue is still there on VS for Mac (can't test VS on Windows currently due to network config here). This issue is at least present since VS for Mac 8.4 and was never gone.

**Comment by Sebastian1989101** [comment]
Here is a project that clearly shows this issue: 
[ODRBug.zip](https://github.com/xamarin/xamarin-macios/files/4524823/ODRBug.zip)

This is my current VS for Mac info: 
```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.5.4 (build 12)
Installation UUID: 4f5a765e-ea38-4825-804a-0b1471e55be2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.2
	1.0.5

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.4.1 (16137)
Build 11E503a

=== Xamarin.Mac ===

Version: 6.16.0.13 (Visual Studio Enterprise)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:18-0400

=== Xamarin.iOS ===

Version: 13.16.0.13 (Visual Studio Enterprise)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:19-0400

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

=== Xamarin.Android ===

Version: 10.2.0.100 (Visual Studio Enterprise)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/sebastian/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/sebastian/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-04-15 20:49:08 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5~1
Build date: 2020-04-15 20:49:28 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805040012
Git revision: 7642369422103e19b0b8d29ddc211abf2fd32607
Build date: 2020-04-16 08:55:15-04
Build branch: release-8.5
Xamarin extensions: 7642369422103e19b0b8d29ddc211abf2fd32607

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64


```
