### ISSUE TITLE
Strange build failures when building project in directory with question marks in path

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#8366]
### Steps to Reproduce

1. Create new iOS project
2. `mkdir \?\?\?`
3. move iOS project to question directory
4. $ msbuild \?\?\?/Question/Question.sln 

```
Microsoft (R) Build Engine version 16.6.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 4/13/2020 10:39:20 AM.
Project "/Users/donblas/tmp/dir/???/Question/Question.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|iPhoneSimulator".
Project "/Users/donblas/tmp/dir/???/Question/Question.sln" (1) is building "/Users/donblas/tmp/dir/???/Question/Question.csproj" (2) on node 1 (default targets).
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/xbuild/Current/Microsoft.Common.props(62,3): error MSB4019: The imported project "/Users/donblas/tmp/dir/???/Question/obj/Question.csproj.*.props" was not found. Confirm that the expression in the Import declaration "/Users/donblas/tmp/dir/%3f%3f%3f/Question/obj/Question.csproj.*.props" is correct, and that the file exists on disk. [/Users/donblas/tmp/dir/???/Question/Question.csproj]
Done Building Project "/Users/donblas/tmp/dir/???/Question/Question.csproj" (default targets) -- FAILED.
Done Building Project "/Users/donblas/tmp/dir/???/Question/Question.sln" (default targets) -- FAILED.
```

Originally from: https://developercommunity.visualstudio.com/content/problem/981949/systemioioexception-read-only-file-system-error-in.html?childToView=987136#comment-987136

### Expected Behavior

Should this even work, I guess escaped question marks are valid?

### Actual Behavior

Failures

### Environment

d16-5 stable.

**Comment by GaryGormley** [comment]
@chamons 
The original issue has been solved. There was more than one volume on my newer Mac with the same name but with different mounts. So I copied the entire solution to the main start disk's primary volume, and the build completes without issue. This explains why another older Mac had no build issues. And I've unmounted the duplicate volume as well.

**Comment by jonathanpeppers** [comment]
@chamons is this resolved? should we close this?

The error coming from `Microsoft.Common.props(62,3)` would actually be from:

https://github.com/microsoft/msbuild/blob/bee129d1b5adaab3826926afb5f54c12e2d4edb4/src/Tasks/Microsoft.Common.props#L62

So I think it's just a general MSBuild issue on macOS with `.sln` files?

**Comment by chamons** [comment]
@jonathanpeppers if the repo steps:
```
    Create new iOS project
    mkdir \?\?\?
    move iOS project to question directory
    $ msbuild ???/Question/Question.sln
```
Work, then sure. But I expect that the user in question just moved their project to a sane folder.

I expect this will stay open but not fixed for a significant timeframe.

**Comment by jonathanpeppers** [comment]
The comment: https://github.com/xamarin/xamarin-macios/issues/8366#issuecomment-613209601

Just says: `The original issue has been solved. `

I think the fix would be in https://github.com/microsoft/msbuild, should this issue be moved there?

**Comment by chamons** [comment]
If you can reproduce with a netcore or console app, yes.

**Comment by jonathanpeppers** [comment]
Closing in favor of: https://github.com/microsoft/msbuild/issues/5407

It happens with a `.sln` file containing a single `netstandard2.0` assembly. Happens with `dotnet build` *and* `msbuild`.
